### ISSUE TITLE
Why are you excluding "assets" in _config.yml?

### ISSUE THREAD

**Issue by joshualinog** [fredericpfisterer/Jekyll-Gulp#3]
![image](https://user-images.githubusercontent.com/1839603/27376890-6c8f8fd0-5641-11e7-82a4-7463e277751c.png)

I'm wondering why the assets folder is excluded? i commented this out because, while it works fine locally, it stops github pages from generating the assets folder when i push it remote. 

will commenting it out create any undesirable behavior you are aware of? great repo btw 💯

**Comment by fredericpfisterer** [comment]
Hello,

I do not want Jekyll to process the assets folder. Gulp is taking care of it so it can do its magic :-)
