### ISSUE TITLE
Migrating away from bower...

### ISSUE THREAD

**Issue by joshualinog** [fredericpfisterer/Jekyll-Gulp#4]
was checking this out:
https://bower.io/blog/2017/how-to-migrate-away-from-bower/

i use you codebase for developing jekyll websites that go live to cloudcannon.

do you have any margin to replace bower in this project with yarn (or something else)?

**Comment by joshualinog** [comment]
i actually just found your webpack branch...

i tried to install it and ran into this error:

![image](https://user-images.githubusercontent.com/1839603/38054752-d9e5ef02-32a5-11e8-8980-9416c61c015b.png)

**Comment by joshualinog** [comment]
it was actuall babel loader:

![image](https://user-images.githubusercontent.com/1839603/38055255-2fd983a0-32a7-11e8-88b8-97b14b52f391.png)

i downgraded it to 7.1.1 per this thread:

https://github.com/babel/babel-loader/issues/505

**Comment by joshualinog** [comment]
so i have it up and running, and i'm using the package.json file to declare dependencies; but my question is, do i need to handwrite my require statements in app.js? or is there a way to automate this with gulp?

**Comment by joshualinog** [comment]
Was there any reason you didn't include a webpack config file?

**Comment by joshualinog** [comment]
I see, it looks like you put the config in an object inside the gulpfile.js file:

![image](https://user-images.githubusercontent.com/1839603/38112993-9bf7dc24-3371-11e8-9188-34393295f739.png)

**Comment by joshualinog** [comment]
i hate that i am having to write the item in twice; is there any way to auto pull dependencies from package.json into app.js without having to manually declare 'require' statements?(kind of like wiredep did for bower...)

**Comment by fredericpfisterer** [comment]
Hello,

I have actually moved to another way of doing all of it :-)

Check my new repo : https://github.com/fredericpfisterer/jekyll-mix

Cheers
